version: "3.9"
services:
  notaryshot-adapter:
    image: "chainhackers/quantumoracle-adapter:latest"
    ports:
      - "9000:9000"
    environment:
      - TWITTER_USERNAME=@XXXXXX_FIXME
      - TWITTER_PASSWORD=XXXXXXXXXXXXX_FIXME
      - TWITTER_EMAIL=XXXXXXXXXX@MY_MAIL_DOMAIN_FIXME
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 600s
  redis:
    image: "redis:alpine"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  chrome:
    image: "browserless/chrome:1-chrome-stable"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
